version: '3.8'

services:
  ncm-app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        - VITE_SUPABASE_URL=${VITE_SUPABASE_URL}
        - VITE_SUPABASE_ANON_KEY=${VITE_SUPABASE_ANON_KEY}
        - VITE_STRIPE_PUBLISHABLE_KEY=${VITE_STRIPE_PUBLISHABLE_KEY}
        - VITE_APP_NAME=${VITE_APP_NAME}
        - VITE_APP_URL=${VITE_APP_URL}
        - VITE_STRIPE_ANNUAL_PRICE_ID=${VITE_STRIPE_ANNUAL_PRICE_ID}
        - VITE_STRIPE_LIFETIME_PRICE_ID=${VITE_STRIPE_LIFETIME_PRICE_ID}
    container_name: ncm-analyzer-pro
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    environment:
      - NGINX_HOST=ncmanalyzerpro.com.br
      - NGINX_PORT=80
    networks:
      - ncm-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # SSL Proxy with Let's Encrypt
  nginx-proxy:
    image: nginxproxy/nginx-proxy:alpine
    container_name: nginx-proxy
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:ro
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
    networks:
      - ncm-network
    depends_on:
      - ncm-app

  # Let's Encrypt companion
  letsencrypt:
    image: nginxproxy/acme-companion
    container_name: letsencrypt
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - nginx-certs:/etc/nginx/certs:rw
      - nginx-vhost:/etc/nginx/vhost.d
      - nginx-html:/usr/share/nginx/html
      - acme:/etc/acme.sh
    environment:
      - DEFAULT_EMAIL=admin@ncmanalyzerpro.com.br
      - NGINX_PROXY_CONTAINER=nginx-proxy
    networks:
      - ncm-network
    depends_on:
      - nginx-proxy

volumes:
  nginx-certs:
  nginx-vhost:
  nginx-html:
  acme:

networks:
  ncm-network:
    driver: bridge